# Dicionário com os DDDs e os estados
ddd = {
    61: "Distrito Federal",
    71: "Bahia",
    11: "São Paulo",
    21: "Rio de Janeiro",
    32: "Minas Gerais",
    27: "Espírito Santo",
    31: "Minas Gerais",
    41: "Paraná",
    53: "Rio Grande do Sul",
    62: "Goiás",
    63: "Tocantins",
    66: "Mato Grosso",
    67: "Mato Grosso do Sul",
    77: "Bahia",
    82: "Alagoas",
    83: "Paraíba",
    84: "Rio Grande do Norte",
    85: "Ceará",
    86: "Piauí",
    87: "Pernambuco",
    88: "Ceará",
    89: "Piauí",
    91: "Pará",
    92: "Amazonas",
    93: "Pará",
    95: "Rio Grande do Sul",
    98: "Maranhão",
}
codigo_ddd = int(input())
print(ddd[codigo_ddd])